subject_id_col: subject_id
hosp/admissions:
  ed_registration:
    code: ED_REGISTRATION
    time: col(edregtime)
    time_format: "%Y-%m-%d %H:%M:%S"
  ed_out:
    code: ED_OUT
    time: col(edouttime)
    time_format: "%Y-%m-%d %H:%M:%S"
  admission:
    code:
      - HOSPITAL_ADMISSION
      - col(admission_type)
      - col(admission_location)
    time: col(admittime)
    time_format: "%Y-%m-%d %H:%M:%S"
    insurance: insurance
    language: language
    marital_status: marital_status
    race: race
    hadm_id: hadm_id
  discharge:
    code:
      - HOSPITAL_DISCHARGE
      - col(discharge_location)
    time: col(dischtime)
    time_format: "%Y-%m-%d %H:%M:%S"
    hadm_id: hadm_id
  # We omit the death event here as it is joined to the data in the subjects table in the pre-MEDS step.

hosp/diagnoses_icd:
  diagnosis:
    code:
      - DIAGNOSIS
      - ICD
      - col(icd_version)
      - col(icd_code)
    hadm_id: hadm_id
    time: col(dischtime)
    time_format: "%Y-%m-%d %H:%M:%S"

hosp/drgcodes:
  drg:
    code:
      - DRG
      - col(drg_type)
      - col(drg_code)
      - col(description)
    hadm_id: hadm_id
    time: col(dischtime)
    time_format: "%Y-%m-%d %H:%M:%S"
    drg_severity: drg_severity
    drg_mortality: drg_mortality

hosp/emar:
  medication:
    code:
      - MEDICATION
      - col(medication)
      - col(event_txt)
    time: col(charttime)
    time_format: "%Y-%m-%d %H:%M:%S"
    hadm_id: hadm_id
    emar_id: emar_id
    emar_seq: emar_seq

hosp/hcpcsevents:
  hcpcs:
    code:
      - HCPCS
      - col(short_description)
    hadm_id: hadm_id
    time: col(chartdate)
    time_format: "%Y-%m-%d"

hosp/labevents:
  lab:
    code:
      - LAB
      - col(itemid)
      - col(valueuom)
    hadm_id: hadm_id
    time: col(charttime)
    time_format: "%Y-%m-%d %H:%M:%S"
    numeric_value: valuenum
    text_value: value
    priority: priority

hosp/omr:
  omr:
    code: col(result_name)
    text_value: col(result_value)
    time: col(chartdate)
    time_format: "%Y-%m-%d"

hosp/patients:
  gender:
    code:
      - GENDER
      - col(gender)
    time: null
  dob:
    code: MEDS_BIRTH # This is the MEDS official code for birth.
    time: col(year_of_birth)
    time_format: "%Y"
  death:
    code: MEDS_DEATH # This is the MEDS official code for death.
    time: col(dod)
    time_format:
      - "%Y-%m-%d %H:%M:%S"
      - "%Y-%m-%d"

hosp/procedures_icd:
  procedure:
    code:
      - PROCEDURE
      - ICD
      - col(icd_version)
      - col(icd_code)
    hadm_id: hadm_id
    time: col(chartdate)
    time_format: "%Y-%m-%d"

hosp/transfers:
  transfer:
    code:
      - TRANSFER_TO
      - col(eventtype)
      - col(careunit)
    time: col(intime)
    time_format: "%Y-%m-%d %H:%M:%S"
    hadm_id: hadm_id

icu/icustays:
  icu_admission:
    code:
      - ICU_ADMISSION
      - col(first_careunit)
    time: col(intime)
    time_format: "%Y-%m-%d %H:%M:%S"
    hadm_id: hadm_id
    icustay_id: stay_id
  icu_discharge:
    code:
      - ICU_DISCHARGE
      - col(last_careunit)
    time: col(outtime)
    time_format: "%Y-%m-%d %H:%M:%S"
    hadm_id: hadm_id
    icustay_id: stay_id
